# Excavator auto-updates this file. Please contribute improvements to the central template.

auto-label:
  names:
    versions-props/upgrade-all: [ "merge when ready" ]
  tags:
    donotmerge: [ "do not merge" ]
    roomba: [ "merge when ready", "🤖 fix nits" ]
    swiffer: [ "merge when ready" ]
    automerge: [ "merge when ready", "🤖 fix nits" ]
    standards: [ "merge when ready", "🤖 fix nits" ]
    autorelease: [ "autorelease" ]
