palantir_aliases:
  - &always-run
    filters:
      branches:
        only: /.*/
      tags:
        only: /.*/

version: 2.1
jobs:
  test:
    parameters:
      python_version:
        type: string
    docker:
      - image: cimg/python:<< parameters.python_version >>
    steps:
      - checkout
      - run: poetry install
      - run: poetry run test

  mypy:
    docker:
      - image: cimg/python:3.12
    steps:
      - checkout
      - run: poetry install
      - run: poetry run check_mypy

  check_format:
    docker:
      - image: cimg/python:3.12
    steps:
      - checkout
      - run: poetry install
      - run: poetry run check_format

  circle-all:
    docker:
      - image: node:lts
    steps:
      - run: echo "Done!"

  publish:
    docker:
      - image: cimg/python:3.12
    steps:
      - checkout
      - run: poetry install
      - run: poetry run set_version
      - run: poetry publish -v -u $PYPI_USERNAME -p $PYPI_PASSWORD --build

workflows:
  version: 2
  build:
    jobs:
      - test:
          <<: *always-run
          name: python-<< matrix.python_version>>
          matrix:
            parameters:
              python_version: ["3.9", "3.10", "3.11", "3.12"]
      - mypy:
        <<: *always-run
      - check_format:
        <<: *always-run
      - circle-all:
          <<: *always-run
          requires:
            - python-3.9
            - python-3.10
            - python-3.11
            - python-3.12

            - mypy
            - check_format
      - publish:
          requires:
            - circle-all
          filters:
            tags: { only: '/^[0-9]+(\.[0-9]+)+(-[a-zA-Z]+[0-9]*)*$/' }
            branches: { ignore: /.*/ }